### ISSUE TITLE
Uvoz in poročilo

### ISSUE THREAD

**Issue by jaanos** [tinarazic/APPR-2017#2]
Svetujem, da tudi v imenih stolpcev ne uporabljaš šumnikov in presledkov (pa tudi ostalih posebnih znakov) - opažam, da sem to spregledal v #1.

Gradnjo tabele `starost` si nekoliko zakomplicirala - ker sta razpredelnici za vsak spol že v obliki *tidy data*, je najlažje, če novo razpredelnico dobiš tako, da po stolpcih združiš razpredelnici z dodanim stolpcem:
```R
starost <- rbind(Mstarost %>% mutate(spol = "M"),
                 Fstarost %>% mutate(spol = "F")) %>%
  transmute(leto = parse_number(leto), drzava, spol = factor(spol), `povprecna starost`)
```
Tako se ohranijo vse vrstice (s tvojim načinom se je ena izgubila). Če bi ime stolpca `povprecna starost` nadomestila s `povprecna.starost` (pika namesto presledka), ga ne bi bilo potrebno dajati med \`\`. Funkcija `mutate` doda nove stolpce, funkcija `transmute` (obe iz `dplyr`) pa stolpce nadomesti z navedenimi - v tem primeru iz stolpca `leto` naredi število, iz stolpca `spol` pa faktor. Stolpec `drzava` je že bil faktor.

Da se ti v poročilu seznami lepo prikažejo, pusti presledek za `-`. Imena tabel imaš lahko kot podnaslove - če na začetku vrstice postaviš `##`, se bo vrstica prikazala kot podnaslov (če uporabiš še več znakov `#`, bo naslov ustrezno manjši). Iz svojih podatkov poskusi tudi izrisati še kak graf.

**Comment by jaanos** [comment]
Naj samo spomnim, da urediš zgornje, da boš pripravljena za ponedeljkovo predstavitev. Opažam sicer še, da je stolpec `povprecna starost` razpredelnice `starost` faktor (zaradi manjkajočih vrednosti, ki so predstavljene z nizom `:(b)`) - da ga pretvoriš v število, lahko torej združitev opraviš tako:
```R
starost <- rbind(Mstarost %>% mutate(spol = "M"),
                 Fstarost %>% mutate(spol = "F")) %>%
  transmute(leto = parse_number(leto), drzava, spol = factor(spol),
            povprecna.starost = parse_number(`povprecna starost`, na = ":(b)"))
```

Trenutno narediš dva grafa, pri katerih države prikažeš z barvami, spol pa z debelino črte. Ker prikazuješ vse države, je graf neberljiv - raje izberi podmnožico držav, ki jih hočeš prikazati (uporabi `filter`). Namesto debeline črte (`size`) raje uporabi tip črte (`linetype` - polna ali črtkana črta). Raje kot `geom_path` uporabi `geom_line`, saj pri slednji dobiš graf, kjer črta povezuje podatke z naraščajočo vrednostjo na osi x, ne glede na dejansko ureditev.

Pri zemljevidu dobiš v legendi eksponentno notacijo - da se je znebiš, lahko podatke deliš z ustreznim številom (seveda naj bo v oznaki jasno, kaj številke prikazujejo). Da ne dobiš opozorila o združevanju faktorja z znakovnim vektorjem, lahko slednjega ustrezno pretvoriš, npr.
```R
g3 <- ggplot() + 
  geom_polygon(data = left_join(evropa,
                                poroke %>% filter(leto == 2015) %>%
                                  mutate(drzava = parse_factor(drzava, levels(evropa$name_long))),
                                by = c("name_long" = "drzava")),
               aes(x = long, y = lat, group = group, 
                   fill = stevilo_porok/1000)) + 
  coord_map(xlim = c(-25, 40), ylim = c(32, 72)) +
  guides(fill = guide_colorbar(title = "Poroke (x 1000)"))
```

V poročilo prosim dodaj grafe in zemljevide, ki jih boš takrat prikazala - teh ne izpisuj v programih v mapi `vizualizacija`, pač pa vsakega prikaži na želenem mestu v poročilu (vsak naj bo v svojem bloku kode). S številom grafov in zemljevidov seveda ni potrebno pretiravati - za vsakega pa napiši, kaj prikazuje in kaj si se iz njega naučila.

**Comment by jaanos** [comment]
Glede na to, da ti poročilo prevede, bom dodal povezavo do trenutnega commita na [repozitorij za zagovore](https://github.com/jaanos/APPR-2017-zagovori). Če boš do predstavitve še kaj spreminjala, odpri issue na repozitoriju za zagovore, da posodobim povezavo - tam si preberi natančnejša navodila.

**Comment by tinarazic** [comment]
Hvala za navodila. 

Sem spremenila in popravila.

Problem imam sedaj pri grafu za povprečno starost. Če pogledate v mapi vizualizacija datotetko g.starost imam v komentarju napisano kaj bi želela narediti, vendar mi ne uspe?

PS: issue na repozitoriju za zagovore bom naredila, ko zaključim z urejanjem pred predstavitvijo.

**Comment by jaanos** [comment]
Želeno lahko dosežeš tako, da v `aes` dodaš parametra `linetype = factor(leto)` (da so črte za posamezna leta različnih tipov) in `group = paste(leto, spol)` (da ti naredi črte glede na leto in spol). S pretvorbo leta v faktor posrbiš, da ga `ggplot` razume kot kategorično spremenljivko in ne poskuša uporabiti zvezne lestvice (ki z `linetype` niti ne deluje). Enako lahko narediš tudi pri drugih grafih.

Sicer pa je v primerih, ko imaš na osi x kategorično spremenljivko, bolje narediti stolpčni diagram - samo gibanje črte namreč nima nobenega pomena. Če želiš res prikazati podatke za vsa tri leta in za oba spola, lahko narediš nekaj takega:
```R
g.starost <- ggplot(starost %>% filter(leto > 2012) %>%
                      mutate(povprecna.starost = (povprecna.starost - 20) * ifelse(spol == "M",
                                                                                   1, -1))) +
  aes(x = drzava, y = povprecna.starost, fill = factor(leto)) +
  geom_col(position = "dodge") + geom_hline(yintercept = 0, color = "grey") + coord_flip() +
  xlab("DRŽAVA") + ylab("POVPREČNA STAROST") + guides(fill = guide_legend(title = "Leto")) +
  scale_y_continuous(labels = . %>% abs() %>% { . + 20 })
```
Tukaj podatkom najprej odšteješ 20 (da bodo razlike v stolpcih bolj očitne), nato pa podatke za ženske negiraš, da se bodo za vsak spol podatki prikazali v svojo smer. Za prikaz stolpcev uporabiš `geom_col`, ki naj stolpce različnih barv (torej za različna leta) nariše enega zraven drugega. Ker nikjer v `aes` ne ločiš po spolu, se hkrati narišeta stolpca za oba spola - podatki za ženske so negirani, tako da se stolpci za oba spola ne bodo prekrivali. Za lažje razločevanje narišeš še črto pri ničli, za večjo berljivost pa koordinati še zamenjaš (`coord_flip`). Nazadnje popraviš še oznake osi - zanje vzameš absolutno vrednost, ki ji prišteješ še 20 (kolikor si na začetku odštela od podatkov). Nastali graf ima na levi podatke za ženske, na desni pa za moške (to bi bilo potrebno nekako označiti ali povedati v besedilu).

Je pa res, da je najbrž na takem grafu vseeno še preveč podatkov. Morda se lahko odločiš podatke prikazati samo za eno leto - za spola lahko potem prikažeš stolpca enega zraven drugega (torej barvaš po spolu), ali pa pustiš v taki obliki s podatki v vsako stran (še vedno lahko barvaš po spolu - v tem primeru odstrani `position = "dodge"`).

Mimogrede, v svojem programu grafov ne izpisuj. Namesto tega jih izpiši v poročilu, vsakega v svojem bloku kode na želenem mestu.

**Comment by tinarazic** [comment]
Dokončala sem projekt.rmd vendar me zanima kako izbrišem tisti nepotrebni stavek pri zemljevidu 'Regions....' ?

**Comment by tinarazic** [comment]
Prosila bi tudi če mi naložite zadnji commit na repozitorij za zagovore.

**Comment by jaanos** [comment]
Pri meni poročila ne prevede, saj imata programa `g.trajanje.R` in `zemljevid.stevilo.R` veliko črko v končnici - to popravi v poročilu, da se bo ujemalo.

Da ti ne bo izpisovalo obvestil v poročilo, v glave blokov kode, kjer se to zgodi, dodaj še parameter `message = FALSE`. Poskrbi tudi za lep izgled poročila: da se bodo seznami lepo prikazali, za vsakim začetnim `-` postavi presledek. Presledke postavi tudi za `1.`, `2.`, `3.`, ... - ko naštevaš tabele, ti bo RMarkdown potem to razumel kot oštevilčen seznam (pa tudi sicer se za ločili in pred oklepaji piše presledke).

Še to: pri grafu trajanja kategorije v legendi niso v pravem vrstnem redu. Da bodo v pravem vrstnem redu, lahko stolpec `trajanje` v razpredelnici `dolzina` pretvoriš v urejen faktor za ustrezen vrstni red. To lahko poskrbiš že pri uvozu:
```R
dolzina <- read_csv("podatki/dolzina_zakonske_zveze.csv",
                    locale = locale(encoding = "windows-1250"),
                    skip = 1,
                    col_names = c("leto", "drzava", "trajanje", "izbrisi1", "stevilo", "izbrisi2"),
                    col_types = cols(trajanje = col_factor(c("Less than 1 year",
                                                             "Less than 5 years",
                                                             "10 years",
                                                             "From 15 to 19 years",
                                                             "From 20 to 24 years",
                                                             "25 years or over"),
                                                           ordered = TRUE)),
                    na=c("", " ", ":")) %>% select(-izbrisi1, -izbrisi2) %>% drop_na()
```
Za funkcijo `drop_na` potrebuješ knjižnico `tidyr`. Po takem uvozu bo potrebno le še zamenjati imeni za Nemčijo in Makedonijo - za ostalo je tukaj že poskrbljeno.

Svetujem, da ne uvažaš knjižnice `reshape`, saj zna povzročati probleme. Za funkciji `melt` in `dcast` uvozi knjižnico `reshape2` (ki je tudi že v `libraries.r`).

Ko to urediš, mi javi, da dodam povezavo.

**Comment by tinarazic** [comment]
Sem uredila. Ali vam še vedno ne prevede projekta? Pri meni so povsod male končnice?

**Comment by jaanos** [comment]
Dve datoteki v mapi `vizualizacija` imata veliko končnico, tako da popravi v poročilu, da se bo ujemalo. Če ti na računalniku ne prikaže končnic, lahko preveriš, kako je na [GitHub](https://github.com/tinarazic/APPR-2017/tree/master/vizualizacija)-u.

**Comment by tinarazic** [comment]
Sedaj bi pa moralo iti čez

**Comment by jaanos** [comment]
V redu, zdaj deluje, tako da bom dodal povezavo. Če boš do predstavitve še kaj spreminjala, mi javi, da jo posodobim.
